/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Svg_page.graphql
 * @generated SignedSource<<d378b914ba36379396b881fb137738d1>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Svg_page = {
  title?: ?string;
  value?: ?string;
  blob?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Svg_page",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "title",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "value",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "blob",
      "storageKey": null
    }
  ],
  "type": "Page"
};

module.exports = fragment;
